Traceback (most recent call last):
  File "/ext3/miniforge3/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/ext3/miniforge3/lib/python3.12/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ext3/miniforge3/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ext3/miniforge3/lib/python3.12/asyncio/base_events.py", line 686, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/ext3/miniforge3/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/ext3/miniforge3/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/ext3/miniforge3/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import pandas as pd
import statsmodels.api as sm
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.formula.api as smf
import numpy as np

from matplotlib.colors import LinearSegmentedColormap
from scipy import stats


url = "https://raw.githubusercontent.com/avehtari/ROS-Examples/master/Sesame/data/sesame.csv"
sesame = pd.read_csv(url)
sesame.head()
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mImportError[0m                               Traceback (most recent call last)
Cell [0;32mIn[1], line 1[0m
[0;32m----> 1[0m [38;5;28;01mimport[39;00m [38;5;21;01mpandas[39;00m [38;5;28;01mas[39;00m [38;5;21;01mpd[39;00m
[1;32m      2[0m [38;5;28;01mimport[39;00m [38;5;21;01mstatsmodels[39;00m[38;5;21;01m.[39;00m[38;5;21;01mapi[39;00m [38;5;28;01mas[39;00m [38;5;21;01msm[39;00m
[1;32m      3[0m [38;5;28;01mimport[39;00m [38;5;21;01mmatplotlib[39;00m[38;5;21;01m.[39;00m[38;5;21;01mpyplot[39;00m [38;5;28;01mas[39;00m [38;5;21;01mplt[39;00m

File [0;32m~/.local/lib/python3.12/site-packages/pandas/__init__.py:19[0m
[1;32m     16[0m         _missing_dependencies[38;5;241m.[39mappend([38;5;124mf[39m[38;5;124m"[39m[38;5;132;01m{[39;00m_dependency[38;5;132;01m}[39;00m[38;5;124m: [39m[38;5;132;01m{[39;00m_e[38;5;132;01m}[39;00m[38;5;124m"[39m)
[1;32m     18[0m [38;5;28;01mif[39;00m _missing_dependencies:  [38;5;66;03m# pragma: no cover[39;00m
[0;32m---> 19[0m     [38;5;28;01mraise[39;00m [38;5;167;01mImportError[39;00m(
[1;32m     20[0m         [38;5;124m"[39m[38;5;124mUnable to import required dependencies:[39m[38;5;130;01m\n[39;00m[38;5;124m"[39m [38;5;241m+[39m [38;5;124m"[39m[38;5;130;01m\n[39;00m[38;5;124m"[39m[38;5;241m.[39mjoin(_missing_dependencies)
[1;32m     21[0m     )
[1;32m     22[0m [38;5;28;01mdel[39;00m _hard_dependencies, _dependency, _missing_dependencies
[1;32m     24[0m [38;5;28;01mtry[39;00m:
[1;32m     25[0m     [38;5;66;03m# numpy compat[39;00m

[0;31mImportError[0m: Unable to import required dependencies:
numpy: No module named 'numpy'

